// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRS_Generator.Data;

namespace SRS_Generator.Migrations
{
    [DbContext(typeof(GuildContext))]
    [Migration("20210228032653_add switch request status enum")]
    partial class addswitchrequeststatusenum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("SRS_Generator.Models.Guild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsFarmingGuild");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("SRS_Generator.Models.GuildMember", b =>
                {
                    b.Property<string>("DiscordId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator");

                    b.Property<Guid?>("GuildId");

                    b.Property<bool>("IsGuildMaster");

                    b.Property<string>("Username");

                    b.HasKey("DiscordId");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("SRS_Generator.Models.SwitchRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApprovedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("RequestedByDiscordId");

                    b.Property<Guid?>("SourceGuildId");

                    b.Property<int>("Status");

                    b.Property<Guid?>("TargetGuildId");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByDiscordId");

                    b.HasIndex("SourceGuildId");

                    b.HasIndex("TargetGuildId");

                    b.ToTable("SwitchRequests");
                });

            modelBuilder.Entity("SRS_Generator.Models.GuildMember", b =>
                {
                    b.HasOne("SRS_Generator.Models.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId");
                });

            modelBuilder.Entity("SRS_Generator.Models.SwitchRequest", b =>
                {
                    b.HasOne("SRS_Generator.Models.GuildMember", "RequestedBy")
                        .WithMany("SwitchRequests")
                        .HasForeignKey("RequestedByDiscordId");

                    b.HasOne("SRS_Generator.Models.Guild", "SourceGuild")
                        .WithMany()
                        .HasForeignKey("SourceGuildId");

                    b.HasOne("SRS_Generator.Models.Guild", "TargetGuild")
                        .WithMany()
                        .HasForeignKey("TargetGuildId");
                });
#pragma warning restore 612, 618
        }
    }
}
