// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRS_Generator.Data;

namespace SRS_Generator.Migrations
{
    [DbContext(typeof(GuildContext))]
    partial class GuildContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("SRS_Generator.Models.Guild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateModified");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("SRS_Generator.Models.GuildMember", b =>
                {
                    b.Property<string>("DiscordId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("GuildId");

                    b.Property<bool>("IsGuildMaster");

                    b.Property<string>("Username");

                    b.HasKey("DiscordId");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("SRS_Generator.Models.GuildMember", b =>
                {
                    b.HasOne("SRS_Generator.Models.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId");
                });
#pragma warning restore 612, 618
        }
    }
}
